# Generated by Django 4.2.5 on 2023-10-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0003_logindetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetail',
            old_name='user',
            new_name='username',
        ),
    ]
