# Generated by Django 4.2.5 on 2023-10-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0005_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterProduct',
            fields=[
                ('product_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
