# Generated by Django 4.2.5 on 2023-10-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0006_waterproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBooking',
            fields=[
                ('booking_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('pincode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.district')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.logindetail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.waterproduct')),
            ],
        ),
    ]
