# Generated by Django 4.2.5 on 2023-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0007_waterbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
