# Generated by Django 4.2.5 on 2023-11-03 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0009_address_order_orderaddress_delete_waterbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='watersystemapp.order'),
        ),
    ]
