# Generated by Django 4.2.5 on 2023-11-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0014_remove_address_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('City_ID', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
    ]
