# Generated by Django 4.2.5 on 2023-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0017_userorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
