# Generated by Django 4.2.5 on 2023-11-05 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0019_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
    ]
