# Generated by Django 4.2.5 on 2023-11-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0020_order_delivery_date_time_order_special_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special_instructions',
        ),
    ]
