# Generated by Django 4.2.5 on 2023-11-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0022_remove_address_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='City_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.city'),
        ),
    ]
