# Generated by Django 4.2.5 on 2023-11-07 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0025_addservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('Request_id', models.AutoField(primary_key=True, serialize=False)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('street', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('request_date_time', models.DateTimeField()),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.district')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.addservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
