# Generated by Django 4.2.5 on 2023-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0028_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkingWaterProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
