# Generated by Django 4.2.5 on 2023-11-08 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0029_drinkingwaterproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_date_time', models.DateTimeField()),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('request_date_time', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.district')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.drinkingwaterproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
