# Generated by Django 4.2.5 on 2023-11-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0030_waterorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterorder',
            name='request_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
