# Generated by Django 4.2.5 on 2023-11-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0031_alter_waterorder_request_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.district'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='mobile_number',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
