# Generated by Django 4.2.5 on 2023-11-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0032_remove_workerprofile_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.district'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
