# Generated by Django 4.2.5 on 2023-11-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0033_alter_workerprofile_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
