# Generated by Django 4.2.5 on 2023-11-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0034_remove_workerprofile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.district'),
        ),
    ]
