# Generated by Django 4.2.5 on 2023-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0035_workerprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
