# Generated by Django 4.2.5 on 2023-11-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watersystemapp', '0036_workerprofile_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedWorker',
            fields=[
                ('assigned_worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.servicerequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watersystemapp.workerprofile')),
            ],
        ),
    ]
